name: Release Package to PyPI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.9
        with:
          python_version: "3.9.6"
          poetry_version: "==1.1.12"
          pypi_token: ${{ secrets.PYPI_PASSWORD }}
